// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | ExhibitionsSlice
  | InfoTextSlice
  | EventBlockSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Primary content in *EventBlock → Primary*
 */
export interface EventBlockSliceDefaultPrimary {
  /**
   * test field in *EventBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_block.primary.test
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  test: prismic.RichTextField;
}

/**
 * Primary content in *EventBlock → Items*
 */
export interface EventBlockSliceDefaultItem {
  /**
   * image field in *EventBlock → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event_block.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *EventBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_block.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Maker field in *EventBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_block.items[].maker
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  maker: prismic.RichTextField;
}

/**
 * Default variation for EventBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventBlockSliceDefaultPrimary>,
  Simplify<EventBlockSliceDefaultItem>
>;

/**
 * Slice variation for *EventBlock*
 */
type EventBlockSliceVariation = EventBlockSliceDefault;

/**
 * EventBlock Shared Slice
 *
 * - **API ID**: `event_block`
 * - **Description**: EventBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventBlockSlice = prismic.SharedSlice<
  "event_block",
  EventBlockSliceVariation
>;

/**
 * Primary content in *Exhibitions → Primary*
 */
export interface ExhibitionsSliceDefaultPrimary {
  /**
   * title field in *Exhibitions → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: exhibitions.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * artist name field in *Exhibitions → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: exhibitions.primary.artist_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  artist_name: prismic.RichTextField;

  /**
   * start date field in *Exhibitions → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: exhibitions.primary.start_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  start_date: prismic.DateField;

  /**
   * end date field in *Exhibitions → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: exhibitions.primary.end_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  end_date: prismic.DateField;

  /**
   * header image field in *Exhibitions → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: exhibitions.primary.header_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  header_image: prismic.ImageField<never>;

  /**
   * description field in *Exhibitions → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: exhibitions.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Exhibitions → Items*
 */
export interface ExhibitionsSliceDefaultItem {
  /**
   * images field in *Exhibitions → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: exhibitions.items[].images
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  images: prismic.ImageField<never>;
}

/**
 * Default variation for Exhibitions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExhibitionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExhibitionsSliceDefaultPrimary>,
  Simplify<ExhibitionsSliceDefaultItem>
>;

/**
 * Slice variation for *Exhibitions*
 */
type ExhibitionsSliceVariation = ExhibitionsSliceDefault;

/**
 * Exhibitions Shared Slice
 *
 * - **API ID**: `exhibitions`
 * - **Description**: Exhibitions
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExhibitionsSlice = prismic.SharedSlice<
  "exhibitions",
  ExhibitionsSliceVariation
>;

/**
 * Primary content in *InfoText → Primary*
 */
export interface InfoTextSliceDefaultPrimary {
  /**
   * Text field in *InfoText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: info_text.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for InfoText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InfoTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *InfoText*
 */
type InfoTextSliceVariation = InfoTextSliceDefault;

/**
 * InfoText Shared Slice
 *
 * - **API ID**: `info_text`
 * - **Description**: InfoText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InfoTextSlice = prismic.SharedSlice<
  "info_text",
  InfoTextSliceVariation
>;

/**
 * Default variation for TestSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *TestSlice*
 */
type TestSliceSliceVariation = TestSliceSliceDefault;

/**
 * TestSlice Shared Slice
 *
 * - **API ID**: `test_slice`
 * - **Description**: TestSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestSliceSlice = prismic.SharedSlice<
  "test_slice",
  TestSliceSliceVariation
>;

/**
 * Primary content in *TitleBlock → Primary*
 */
export interface TitleBlockSliceDefaultPrimary {
  /**
   * image field in *TitleBlock → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: title_block.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TitleBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TitleBlock*
 */
type TitleBlockSliceVariation = TitleBlockSliceDefault;

/**
 * TitleBlock Shared Slice
 *
 * - **API ID**: `title_block`
 * - **Description**: TitleBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleBlockSlice = prismic.SharedSlice<
  "title_block",
  TitleBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      EventBlockSlice,
      EventBlockSliceDefaultPrimary,
      EventBlockSliceDefaultItem,
      EventBlockSliceVariation,
      EventBlockSliceDefault,
      ExhibitionsSlice,
      ExhibitionsSliceDefaultPrimary,
      ExhibitionsSliceDefaultItem,
      ExhibitionsSliceVariation,
      ExhibitionsSliceDefault,
      InfoTextSlice,
      InfoTextSliceDefaultPrimary,
      InfoTextSliceVariation,
      InfoTextSliceDefault,
      TestSliceSlice,
      TestSliceSliceVariation,
      TestSliceSliceDefault,
      TitleBlockSlice,
      TitleBlockSliceDefaultPrimary,
      TitleBlockSliceVariation,
      TitleBlockSliceDefault,
    };
  }
}
