// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  event_block: defineAsyncComponent(() => import("./EventBlock/index.vue")),
  info_text: defineAsyncComponent(() => import("./InfoText/index.vue")),
  title_block: defineAsyncComponent(() => import("./TitleBlock/index.vue")),
});
